puddle/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("contact/", views.contact, name="contact"),
    path("signup/", views.signup, name="signup"),
]

puddle/item/urls.py
from django.urls import path
from . import views

app_name = "item"

urlpatterns = [
    path("<int:pk>", views.detail, name="detail"),
]

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Views

urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("items/", include("item.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/core/models.py
from django.db import models

# Create your models here.

puddle/item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Items(models.Model):
    category = models.ForeignKey(
        Category, related_name="items", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    is_sold = models.BooleanField(default=False)
    create_data = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)
    image = models.ImageField(upload_to="item_imgs", blank=True, null=True)

    def __str__(self) -> str:
        return self.name

puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "Your username", "class": "w-full py-3 px-5"}
        )
    )

    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={"placeholder": "Your email", "class": "w-full py-3 px-5"}
        )
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"placeholder": "Your password", "class": "w-full py-3 px-5"}
        )
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"placeholder": "Repeat the password", "class": "w-full py-3 px-5"}
        )
    )

puddle/core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Items
from .forms import SignupForm

# Create your views here.
def index(request):
    items = Items.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(
        request,
        "core\index.html",
        {
            "categories": categories,
            "items": items,
        },
    )


def contact(request):
    return render(request, "core/contact.html")


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect("/login/")
    form = SignupForm()
    return render(request, "core/signup.html", {"form": form})

puddle/item/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from .models import Items

# Create your views here.
def detail(request, pk):
    item = get_object_or_404(Items, pk=pk)
    related_items = Items.objects.filter(category=item.category, is_sold=False).exclude(
        pk=pk
    )[0:3]

    return render(
        request, "item/detail.html", {"item": item, "related_items": related_items}
    )

puddle/core/templates/core/base.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" >
    <mata name="viewport" content="width=device-width, initial-scale=1.0" >
    <script src="https://cdn.tailwindcss.com"></script>
    <title> {% block title %}{% endblock %} | Puddle</title>
  </head>

  <body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-300">
        <a href="/" class="text-xxl font-bold">Puudle</a>
        <div>
            <a href="#" class="text-lg font-semibold hover:text-gray-400">New item</a>
            <a href="#" class="text-lg font-semibold hover:text-gray-400">Browse</a>

            <a href="{%url 'core:signup'%}" class="px-6 py-3 text-lg bg-green-400 text-white rounded-xl hover:bg-green-500">Sign up</a>
            <a href="#" class="px-6 py-3 text-lg bg-teal-400 text-white rounded-xl hover:bg-teal-500">Log in</a>
        </div>
    </nav>
    <div class="px-6 py-6">{% block content %} {% endblock %}</div>

    <footer class="px-6 py-6 flex justify-between bg-gray-700">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-300">{% lorem 1 b random %}</p>
        </div>

        <div>
            <h3 class="mb-5 font-semibold text-gray-500">Menu</h3>

            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-400 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-400 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-400 hover:text-teal-700">Terms and conditions</a></li>
                <li><a href="#" class="text-lg text-teal-400 hover:text-teal-700">Privacy</a></li>
            </ul>
        </div>

    </footer>
  </body>
</html>

puddle/core/templates/core/contact.html
{% extends "core/base.html" %} 
{% block title %} Contact {%endblock%} 
{% block content %}
<h1>Contact page</h1>
{% endblock %}

puddle/core/templates/core/index.html
{% extends "core/base.html" %} 
{% block title %} Index {%endblock%} 
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest items<h2>
    <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
            <div>
                <a href="{% url 'item:detail' item.id%}">
                    <div>
                    {% if item.image %}
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                    {%endif%}
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-xl">{{item.name}}</h2>
                        <p class="text-gray-400">Price: {{item.price}}</p>
                    </div>
                </a>
            </div>
        {%endfor%}
    </div>

    <div class="rounded-xl mt-5 px-6 py-12 bg-gray-100">
        <h2 class="mb-10 text-xl text-center">Categories</h2>

        <div class="gird gird-cols-3 gap-3">
            {%for c in Categories%}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{c.name}}</h2>
                        <p class="text-gray-400">{{c.items.count}}</p>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>
    </div>
</div>
{% endblock %}

puddle/core/templates/core/signup.html
{% extends "core/base.html" %}

{% block title %} Sign Up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl p-6">
    <h1 class="mb-6 text-2xl">Sign up</h1>

    <form method="post" action=".">
        {%csrf_token%}
        <div class="mb-3">
            <label class="inline-block mb-2"> Username </label><br>
            {{form.username}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2"> Email </label><br>
            {{form.email}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2"> Password </label><br>
            {{form.password1}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2"> Repeat password </label><br>
            {{form.password2}}
        </div>
        {% if form.errors or form.non_field_error%}
            <div class="mb-3 p-6 bg-red-200 rounded-xl">
                {%for field in form %}
                    {{field.errors}}
                {%endfor%}
                {{form.non_field_error}}
            </div>
        {%endif%}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-green-200 rounded-xl text-white">Create user</button>
    </form>
</div>
{% endblock %}

puddle/item/templates/item/detail.html
{% extends "core/base.html" %}

{% block title %}
{{item.name}}
{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    {%if item.image%}
    <div class="col-span-3">
        <img src="{{item.image.url}}" class="rounded-xl">
    </div>    
    {%endif%}
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        {% if item.name %}
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        {%endif%}
        {% if item.price %}
        <p class="text-gray-500"><strong>Price: {{item.price}}</strong></p>
        {%endif%}
        {% if item.created_by %}
        <p class="text-gray-500"><strong>Seller: {{item.created_by}}</strong></p>
        {% endif %}
        {%if item.description %}
        <p class="text-gray-700">
            <strong class="text-gray-500">Description: </strong><br>
            {{item.description}}
        </p>
        {%endif%}

        <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-600 text-white rounded-xl hover:bg-green-300">Contact seller</a>
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related items<h2>
    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
            <div>
                <a href="{% url 'item:detail' item.id%}">
                    <div>
                    {% if item.image %}
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                    {%endif%}
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-xl">{{item.name}}</h2>
                        <p class="text-gray-400">Price: {{item.price}}</p>
                    </div>
                </a>
            </div>
        {%endfor%}
    </div>

    <div class="rounded-xl mt-5 px-6 py-12 bg-gray-100">
        <h2 class="mb-10 text-xl text-center">Categories</h2>

        <div class="gird gird-cols-3 gap-3">
            {%for c in Categories%}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{c.name}}</h2>
                        <p class="text-gray-400">{{c.items.count}}</p>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>
    </div>
</div>

{% endblock %}